module.exports={
	port:"8081",
	host:"static.baiten.cn",
  	root:"D:/devworkspace/git/web-protal-frontend-release0.1/platform-frontend-site/src/main/webapp/frontlib",  
    js:"js",
    css:"css",
    img:"images",
    templateHtml:"templateHtml",
    imagebuild:['images/**/*.{png,jpg,gif}'],
    template:"templateHtml/patent/**/*.html",
	gruntFile:["bra/**/**.js","tpl/**/*.js"],     
	tpldest:"../tpl",
	dest:"assets",  
	spm:{
		"base":"/js/sea-modules",
		"alias":{
			"$":"gallery/jquery/jquery-1.10.2.min.js",
			"cookie":"gallery/jquery.cookie/jquery.cookie.js",
			"template":"gallery/template/template.min.js",
			"jquery-validate":"gallery/jquery.validate/jquery.validate.js",
			"datapicker":"gallery/My97DatePicker/WdatePicker.js",
			 "placeholder":"gallery/jquery.placeholders/placeholder.js"
		}
	}
}